### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by braceal** [DeepDriveMD/GordonBell#1]
- [x] Which CUDA module to load for NAMD runs?
- [x] Decide on whether or not to tune hyperparameters. Could simply use a pretrained model and do fine tuning for 1 HP config.
- [x] Add pretrained model weights 
- [x] Verify correct version of NAMD and load correct modules in pre_exec
- [x] How many MD jobs to run?
- [x] Config cutoff = 8 ?
- [x] Config selection ?
- [x] Update ddmd to receive a list of PDBs
